/* SPDX-License-Identifier: MIT */
#ifndef RINERROR_ERROR_H
#define RINERROR_ERROR_H

#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

#define RIN_ERROR_VERSION_1 1u

typedef enum RinErrorDomain {
    RINERROR_DOMAIN_ERRNO = 1u,
    RINERROR_DOMAIN_NEGATIVE_SYSCALL = 2u,
    RINERROR_DOMAIN_RIN_SDK = 3u,
    RINERROR_DOMAIN_RIN_RESULT = 4u,
    RINERROR_DOMAIN_IPC = 5u,
    RINERROR_DOMAIN_ENUM_STATUS = 6u,
    RINERROR_DOMAIN_WIN32 = 7u
} RinErrorDomain;

typedef enum RinErrorKind {
    RINERROR_KIND_SUCCESS = 0u,
    RINERROR_KIND_INVALID_ARGUMENT = 1u,
    RINERROR_KIND_NOT_FOUND = 2u,
    RINERROR_KIND_PERMISSION_DENIED = 3u,
    RINERROR_KIND_RESOURCE_EXHAUSTED = 4u,
    RINERROR_KIND_ALREADY_EXISTS = 5u,
    RINERROR_KIND_BUSY = 6u,
    RINERROR_KIND_TIMEOUT = 7u,
    RINERROR_KIND_CANCELLED = 8u,
    RINERROR_KIND_IO = 9u,
    RINERROR_KIND_WOULD_BLOCK = 10u,
    RINERROR_KIND_MALFORMED = 11u,
    RINERROR_KIND_STALE = 12u,
    RINERROR_KIND_REVOKED = 13u,
    RINERROR_KIND_UNSUPPORTED = 14u,
    RINERROR_KIND_INTEGRITY = 15u,
    RINERROR_KIND_DEVICE_LOST = 16u,
    RINERROR_KIND_INTERRUPTED = 17u,
    RINERROR_KIND_UNKNOWN = 18u
} RinErrorKind;

/* Legacy RIN_ERROR_* names are opt-in because the public SDK uses the same
 * prefix for its negative RinResult values.  Mixed SDK consumers must use
 * the unambiguous RINERROR_* names above. */
#if defined(RINERROR_LEGACY_NAMES)
#define RIN_ERROR_DOMAIN_ERRNO RINERROR_DOMAIN_ERRNO
#define RIN_ERROR_DOMAIN_NEGATIVE_SYSCALL RINERROR_DOMAIN_NEGATIVE_SYSCALL
#define RIN_ERROR_DOMAIN_RIN_SDK RINERROR_DOMAIN_RIN_SDK
#define RIN_ERROR_DOMAIN_RIN_RESULT RINERROR_DOMAIN_RIN_RESULT
#define RIN_ERROR_DOMAIN_IPC RINERROR_DOMAIN_IPC
#define RIN_ERROR_DOMAIN_ENUM_STATUS RINERROR_DOMAIN_ENUM_STATUS
#define RIN_ERROR_DOMAIN_WIN32 RINERROR_DOMAIN_WIN32
#define RIN_ERROR_SUCCESS RINERROR_KIND_SUCCESS
#define RIN_ERROR_INVALID_ARGUMENT RINERROR_KIND_INVALID_ARGUMENT
#define RIN_ERROR_NOT_FOUND RINERROR_KIND_NOT_FOUND
#define RIN_ERROR_PERMISSION_DENIED RINERROR_KIND_PERMISSION_DENIED
#define RIN_ERROR_RESOURCE_EXHAUSTED RINERROR_KIND_RESOURCE_EXHAUSTED
#define RIN_ERROR_ALREADY_EXISTS RINERROR_KIND_ALREADY_EXISTS
#define RIN_ERROR_BUSY RINERROR_KIND_BUSY
#define RIN_ERROR_TIMEOUT RINERROR_KIND_TIMEOUT
#define RIN_ERROR_CANCELLED RINERROR_KIND_CANCELLED
#define RIN_ERROR_IO RINERROR_KIND_IO
#define RIN_ERROR_WOULD_BLOCK RINERROR_KIND_WOULD_BLOCK
#define RIN_ERROR_MALFORMED RINERROR_KIND_MALFORMED
#define RIN_ERROR_STALE RINERROR_KIND_STALE
#define RIN_ERROR_REVOKED RINERROR_KIND_REVOKED
#define RIN_ERROR_UNSUPPORTED RINERROR_KIND_UNSUPPORTED
#define RIN_ERROR_INTEGRITY RINERROR_KIND_INTEGRITY
#define RIN_ERROR_DEVICE_LOST RINERROR_KIND_DEVICE_LOST
#define RIN_ERROR_INTERRUPTED RINERROR_KIND_INTERRUPTED
#define RIN_ERROR_UNKNOWN RINERROR_KIND_UNKNOWN
#define RIN_ERROR_FLAG_MALFORMED RINERROR_FLAG_MALFORMED
#define RIN_ERROR_FLAG_REVOKED RINERROR_FLAG_REVOKED
#define RIN_ERROR_FLAG_CANCELLED RINERROR_FLAG_CANCELLED
#define RIN_ERROR_FLAG_RETRYABLE RINERROR_FLAG_RETRYABLE
#define RIN_ERROR_STATUS_OK RINERROR_STATUS_OK
#define RIN_ERROR_STATUS_INVALID_ARGUMENT RINERROR_STATUS_INVALID_ARGUMENT
#define RIN_ERROR_STATUS_BAD_VERSION RINERROR_STATUS_BAD_VERSION
#define RIN_ERROR_STATUS_BAD_FLAGS RINERROR_STATUS_BAD_FLAGS
#define RIN_ERROR_STATUS_BAD_DOMAIN RINERROR_STATUS_BAD_DOMAIN
#define RIN_ERROR_STATUS_BAD_KIND RINERROR_STATUS_BAD_KIND
#endif

enum {
    RINERROR_FLAG_MALFORMED = 0x00000001u,
    RINERROR_FLAG_REVOKED = 0x00000002u,
    RINERROR_FLAG_CANCELLED = 0x00000004u,
    RINERROR_FLAG_RETRYABLE = 0x00000008u
};

typedef enum RinErrorStatus {
    RINERROR_STATUS_OK = 0,
    RINERROR_STATUS_INVALID_ARGUMENT = -1,
    RINERROR_STATUS_BAD_VERSION = -2,
    RINERROR_STATUS_BAD_FLAGS = -3,
    RINERROR_STATUS_BAD_DOMAIN = -4,
    RINERROR_STATUS_BAD_KIND = -5
} RinErrorStatus;

typedef struct RinErrorV1 {
    uint32_t struct_size;
    uint16_t version;
    uint16_t domain;
    int64_t source_code;
    uint32_t kind;
    uint32_t flags;
    int32_t canonical_errno;
    uint32_t reserved;
} RinErrorV1;

int rin_error_validate(const RinErrorV1* error);
int rin_error_from_code(uint16_t domain, int64_t code, RinErrorV1* output);
int rin_error_from_status(uint16_t domain, int64_t code, uint32_t flags,
                          RinErrorV1* output);
int rin_error_from_errno(int error_number, RinErrorV1* output);
int rin_error_from_negative_syscall(intptr_t result, RinErrorV1* output);
int rin_error_from_win32(uint32_t error_code, RinErrorV1* output);

int rin_error_is_success(const RinErrorV1* error);
int rin_error_is_retryable(const RinErrorV1* error);
int rin_error_is_cancellation(const RinErrorV1* error);
int rin_error_is_malformed(const RinErrorV1* error);
int rin_error_is_revoked(const RinErrorV1* error);
int rin_error_to_errno(const RinErrorV1* error);
const char* rin_error_kind_name(uint32_t kind);

#ifdef __cplusplus
}
#endif

#endif /* RINERROR_ERROR_H */
